#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 03.05.2020 16:32
# Generated By: Ali Elchab / Sangeeths Chandrakumar
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#Elemente, Variablen werden für das GUI erstellt und deklariert
$SynkWindow = New-Object System.Windows.Forms.Form
$logfileBox = New-Object System.Windows.Forms.RichTextBox
$FehlermeldungText = New-Object System.Windows.Forms.Label
$stopSynkButton = New-Object System.Windows.Forms.Button
$startSynkButton = New-Object System.Windows.Forms.Button
$ordner2Auswählen = New-Object System.Windows.Forms.Button
$ordner1Auswählen = New-Object System.Windows.Forms.Button
$ordner2textBox = New-Object System.Windows.Forms.TextBox
$ordner2Title = New-Object System.Windows.Forms.Label
$ordner1textBox = New-Object System.Windows.Forms.TextBox
$ordner1Title = New-Object System.Windows.Forms.Label
$openFileDialog1 = New-Object System.Windows.Forms.OpenFileDialog
$openFileDialog2 = New-Object System.Windows.Forms.OpenFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
$global:File1Path = ""
$global:File2Path = ""
$global:pidprocess = $null

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.


#Dieser Button öffnet den Windows Explorer, wenn man drauf klickt
$handler_ordner1Auswählen_Click= 
{
    $OrdnerWahl = New-Object System.Windows.Forms.FolderBrowserDialog
    $OrdnerWahl.ShowNewFolderButton = $false
    $OrdnerWahl.ShowDialog()
    if ($OrdnerWahl.SelectedPath -ne "")            
    {     
        $directory1Info = Get-ChildItem -Path $OrdnerWahl.SelectedPath | Measure-Object
        if($directory1Info.count -eq 0)
        {
            $logfileBox.ForeColor = 'red'
            $logfileBox.AppendText("Der Ordner1 ist leer, hier gibt es nichts zum synken`r")    
        }
        else
        {
            # Gewählter Pfad setzen 
            if($($OrdnerWahl.SelectedPath) -ne $global:File2Path)
            { 
                $global:File1Path = $($OrdnerWahl.SelectedPath)        
                $ordner1textBox.text = $global:File1Path   
            }
            else
            {
                $logfileBox.ForeColor = 'red'
                $logfileBox.AppendText("Der Pfad von Ordner1 ist gleich wie der Pfad von Ordner2`r")    
            }  
        }
      
    } 
}

#Diese Funktion öffnet den Win Explorer für 
#den ersten Ordner auf, wenn Button geklickt ist.
$handler_ordner2Auswählen_Click= 
{
    $OrdnerWahl = New-Object System.Windows.Forms.FolderBrowserDialog
    $OrdnerWahl.ShowNewFolderButton = $false
    $OrdnerWahl.ShowDialog()
    if ($OrdnerWahl.SelectedPath -ne "")            
    {     
        $directory1Info = Get-ChildItem -Path $OrdnerWahl.SelectedPath | Measure-Object
        if($directory1Info.count -eq 0)
        {
            $logfileBox.ForeColor = 'red'
            $logfileBox.AppendText("Der Ordner2 ist leer, hier gibt es nichts zum synken`r")    
        }
        else
        {
            # Gewählter Pfad setzen
            if($($OrdnerWahl.SelectedPath) -ne $global:File1Path)
            {
                 $global:File2Path = $($OrdnerWahl.SelectedPath)        
                 $ordner2textBox.text = $global:File2Path   
            }
            else
            {
                $logfileBox.ForeColor = 'red'
                $logfileBox.AppendText("Der Pfad von Ordner2 ist gleich wie der Pfad von Ordner1`r")    
            }
        }  
    } 
}

$handler_button3_Click= 
{
    if($global:File1Path -ne "" -and $global:File2Path -ne "")
    {
        $logfileBox.Clear()
        $logfileBox.ForeColor = 'green'
        $logfileBox.AppendText("Synk hat erfolgreich gestartet`r")
        $global:pidprocess = start-job -FilePath 'C:\Users\Sangeeths Chandrakum\Desktop\SynkProjekt\SyncFolders.ps1' -argumentlist $global:File1Path,$global:File2Path
        $stopSynkButton.Enabled = $True
        $startSynkButton.Enabled = $False
    }
    else
    {
        $logfileBox.ForeColor = 'red'
        $logfileBox.AppendText("Ordner sind nicht ausgewählt dadurch kann der Synk nicht gestartet werden`r")    
    }
    
}

#Dieser Button stoppt, den Synk
$handler_stopSynkButton_Click= 
{
    $logfileBox.ForeColor = 'green'
    $logfileBox.AppendText("Synk hat erfolgreich beendet`r")
    $global:pidprocess.StopJob()
    $startSynkButton.Enabled = $True
    $stopSynkButton.Enabled = $False
}


#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 348
$System_Drawing_Size.Width = 628
$SynkWindow.ClientSize = $System_Drawing_Size
$SynkWindow.DataBindings.DefaultDataSourceUpdateMode = 0
$SynkWindow.Name = "SynkWindow"
$SynkWindow.Text = "Powershell Synk "

$logfileBox.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 168
$logfileBox.Location = $System_Drawing_Point
$logfileBox.Name = "logfileBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 81
$System_Drawing_Size.Width = 369
$logfileBox.Size = $System_Drawing_Size
$logfileBox.TabIndex = 9
$logfileBox.Text = ""
$logfileBox.Enabled = $False

$SynkWindow.Controls.Add($logfileBox)

$FehlermeldungText.DataBindings.DefaultDataSourceUpdateMode = 0
$FehlermeldungText.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",14.25,0,3,0)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 136
$FehlermeldungText.Location = $System_Drawing_Point
$FehlermeldungText.Name = "FehlermeldungText"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 28
$System_Drawing_Size.Width = 157
$FehlermeldungText.Size = $System_Drawing_Size
$FehlermeldungText.TabIndex = 8
$FehlermeldungText.Text = "Logfile"
$FehlermeldungText.add_Click($handler_FehlermeldungText_Click)

$SynkWindow.Controls.Add($FehlermeldungText)


$stopSynkButton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 144
$System_Drawing_Point.Y = 276
$stopSynkButton.Location = $System_Drawing_Point
$stopSynkButton.Name = "stopSynkButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 38
$System_Drawing_Size.Width = 100
$stopSynkButton.Size = $System_Drawing_Size
$stopSynkButton.TabIndex = 7
$stopSynkButton.Text = "Stop Button"
$stopSynkButton.UseVisualStyleBackColor = $True
$stopSynkButton.add_Click($handler_stopSynkButton_Click)
$stopSynkButton.Enabled = $False
$SynkWindow.Controls.Add($stopSynkButton)


$startSynkButton.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 276
$startSynkButton.Location = $System_Drawing_Point
$startSynkButton.Name = "startSynkButton"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 38
$System_Drawing_Size.Width = 101
$startSynkButton.Size = $System_Drawing_Size
$startSynkButton.TabIndex = 6
$startSynkButton.Text = "Start Synk"
$startSynkButton.UseVisualStyleBackColor = $True
$startSynkButton.add_Click($handler_button3_Click)

$SynkWindow.Controls.Add($startSynkButton)


$ordner2Auswählen.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 511
$System_Drawing_Point.Y = 63
$ordner2Auswählen.Location = $System_Drawing_Point
$ordner2Auswählen.Name = "ordner2Auswählen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ordner2Auswählen.Size = $System_Drawing_Size
$ordner2Auswählen.TabIndex = 5
$ordner2Auswählen.Text = "auswählen"
$ordner2Auswählen.UseVisualStyleBackColor = $True
$ordner2Auswählen.add_Click($handler_ordner2Auswählen_Click)

$SynkWindow.Controls.Add($ordner2Auswählen)


$ordner1Auswählen.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 511
$System_Drawing_Point.Y = 20
$ordner1Auswählen.Location = $System_Drawing_Point
$ordner1Auswählen.Name = "ordner1Auswählen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$ordner1Auswählen.Size = $System_Drawing_Size
$ordner1Auswählen.TabIndex = 4
$ordner1Auswählen.Text = "auswählen"
$ordner1Auswählen.UseVisualStyleBackColor = $True
$ordner1Auswählen.add_Click($handler_ordner1Auswählen_Click)

$SynkWindow.Controls.Add($ordner1Auswählen)

$ordner2textBox.DataBindings.DefaultDataSourceUpdateMode = 0
$ordner2textBox.Enabled = $False
$ordner2textBox.ForeColor = [System.Drawing.Color]::FromArgb(255,160,160,160)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 104
$System_Drawing_Point.Y = 63
$ordner2textBox.Location = $System_Drawing_Point
$ordner2textBox.Name = "ordner2textBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 390
$ordner2textBox.Size = $System_Drawing_Size
$ordner2textBox.TabIndex = 3
$ordner2textBox.Text = "Bitte auswählen"

$SynkWindow.Controls.Add($ordner2textBox)

$ordner2Title.DataBindings.DefaultDataSourceUpdateMode = 0
$ordner2Title.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",14.25,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 63
$ordner2Title.Location = $System_Drawing_Point
$ordner2Title.Name = "ordner2Title"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$ordner2Title.Size = $System_Drawing_Size
$ordner2Title.TabIndex = 2
$ordner2Title.Text = "Ordner 2"

$SynkWindow.Controls.Add($ordner2Title)

$ordner1textBox.DataBindings.DefaultDataSourceUpdateMode = 0
$ordner1textBox.Enabled = $False
$ordner1textBox.ForeColor = [System.Drawing.Color]::FromArgb(255,160,160,160)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 104
$System_Drawing_Point.Y = 23
$ordner1textBox.Location = $System_Drawing_Point
$ordner1textBox.Name = "ordner1textBox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 390
$ordner1textBox.Size = $System_Drawing_Size
$ordner1textBox.TabIndex = 1
$ordner1textBox.Text = "Bitte auswählen"
$ordner1textBox.add_TextChanged($handler_ordner1textBox_TextChanged)

$SynkWindow.Controls.Add($ordner1textBox)

$ordner1Title.DataBindings.DefaultDataSourceUpdateMode = 0
$ordner1Title.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",14.25,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 20
$ordner1Title.Location = $System_Drawing_Point
$ordner1Title.Name = "ordner1Title"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 101
$ordner1Title.Size = $System_Drawing_Size
$ordner1Title.TabIndex = 0
$ordner1Title.Text = "Ordner 1"
$ordner1Title.add_Click($handler_label1_Click)

$SynkWindow.Controls.Add($ordner1Title)

$openFileDialog1.FileName = "openFileDialogOrdner1"
$openFileDialog1.ShowHelp = $True
$openFileDialog1.add_FileOk($handler_openFileDialog1_FileOk)

$openFileDialog2.FileName = "openFileDialogOrdner2"
$openFileDialog2.ShowHelp = $True

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $SynkWindow.WindowState
#Init the OnLoad event to correct the initial state of the form
$SynkWindow.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$SynkWindow.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
